<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rc</string>
		<string>rh</string>
	</array>
	<key>name</key>
	<string>Rapid</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storageSize</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scopeLimit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compilerCode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtinTypes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(if|else|while|for|foreach|switch|match|return|break|continue|defer)\b)</string>
			<key>name</key>
			<string>keyword.control.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(new|delete|soa|aos)\b)</string>
			<key>name</key>
			<string>keyword.other.memory.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(use|import)\b)</string>
			<key>name</key>
			<string>keyword.other.misc.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(readonly|writeonly)\b)</string>
			<key>name</key>
			<string>storage.modifier.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(true|false|null)\b)</string>
			<key>name</key>
			<string>constant.language.source.rapid</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.source.rapid</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.value.source.rapid</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@[A-Za-z]+\()([A-Za-z0-9_., ]+)(\))</string>
					<key>name</key>
					<string>meta.definition.attribute.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(@[A-Za-z]+)</string>
					<key>name</key>
					<string>entity.other.attribute-name.source.rapid</string>
				</dict>
			</array>
		</dict>
		<key>builtinTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\b(bool|i8|i16|i32|i64|u8|u16|u32|u64)\b)</string>
					<key>name</key>
					<string>storage.type.integer.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b(half|float|double|[hfd]vec[234]|[hfd]mat44|[hfd]mat43|[hfd]mat22)\b)</string>
					<key>name</key>
					<string>storage.type.float.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b(void|uchar|string)\b)</string>
					<key>name</key>
					<string>storage.type.misc.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b(auto|any|fn|function|dl|delegate)\b)</string>
					<key>name</key>
					<string>storage.type.auto.source.rapid</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((//).*$\n?)</string>
					<key>name</key>
					<string>comment.line.double-slash.source.rapid</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.rapid</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/\n?</string>
					<key>name</key>
					<string>comment.block.source.rapid</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>compilerCode</key>
		<dict>
			<key>begin</key>
			<string>(##)</string>
			<key>end</key>
			<string>(##)</string>
			<key>name</key>
			<string>entity.other.attribute-name</string>
		</dict>
		<key>functionPrototype</key>
		<dict>
			<key>name</key>
			<string>meta.definition.function.prototype.source.rapid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.function.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\w)(?:[\t ]+)((\.?[A-Za-z0-9_]+)+)\(</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((\b|-)[0-9_]+\.[0-9_]+(e\-[0-9]+)?)</string>
					<key>name</key>
					<string>constant.numeric.float.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((\b|-)[0-9_]+([ul]{1,2})?\b)</string>
					<key>name</key>
					<string>constant.numeric.integer.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b0x[\dA-Fa-f_]+\b)</string>
					<key>name</key>
					<string>constant.numeric.hex.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b0b(0|1)+\b)</string>
					<key>name</key>
					<string>constant.numeric.binary.source.rapid</string>
				</dict>
			</array>
		</dict>
		<key>scopeLimit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[(\s*[A-Za-z0-9_]+,?)*\s*\])(?:\s*\{)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:\))\s(\[(\s*[A-Za-z0-9_]+,?)*\s*\])(?:\s*(\b|\;))</string>
				</dict>
			</array>
		</dict>
		<key>storage</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.storage.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.storage.source.rapid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)^\s*(module|struct|alias)\s+([A-Za-z0-9_]+)\b</string>
			<key>name</key>
			<string>meta.definition.storage.source.rapid</string>
		</dict>
		<key>storageSize</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.rapid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.storage.source.rapid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)^\s*(enum|bits)\s+([A-Za-z0-9_.]+)\s+([A-Za-z0-9_]+)\b</string>
			<key>name</key>
			<string>meta.definition.enum.source.rapid</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.rapid</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.rapid</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.rapid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\.)</string>
					<key>name</key>
					<string>punctuation.definition.string</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.rapid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.source.rapid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b[A-Za-z0-9_]+)\s*([:])\s*([#]?[A-Za-z0-9_]+\b)</string>
			<key>name</key>
			<string>meta.definition.struct.source.rapid</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rapid</string>
	<key>uuid</key>
	<string>cd4e6b22-a322-4771-8eef-91166b808f3d</string>
</dict>
</plist>
