<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rc</string>
		<string>rh</string>
	</array>
	<key>name</key>
	<string>Rapid</string>
	<key>patterns</key>
	<array>
		<false/>
	</array>
	<key>scopeName</key>
	<string>source.rapid</string>
	<key>uuid</key>
	<string>cd4e6b22-a322-4771-8eef-91166b808f3d</string>
</dict>
</plist>
