<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rc</string>
		<string>rh</string>
	</array>
	<key>name</key>
	<string>Rapid</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#struct</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionPrototype</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scopeLimit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compilerCode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(if|else|while|do|for|foreach|switch|match|return|break|continue|defer)\b)</string>
			<key>name</key>
			<string>keyword.control.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(override|final)\b)</string>
			<key>name</key>
			<string>keyword.other.inheritance.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(new|delete)\b)</string>
			<key>name</key>
			<string>keyword.other.memory.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(auto|function|delegate)\b)</string>
			<key>name</key>
			<string>keyword.other.auto.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(public|private|protected|internal|const)\b)</string>
			<key>name</key>
			<string>storage.modifier.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(module|alias|enum|bitmask|operator|attribute|unittest)\b)</string>
			<key>name</key>
			<string>storage.type.core.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(bool|int|int8|int16|int32|int64|int128|uint|uint8|uint16|uint32|uint64|uint128)\b)</string>
			<key>name</key>
			<string>storage.type.integer.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(half|float|double|real|[hfd]?vec[234]|mat44|mat43|mat22)\b)</string>
			<key>name</key>
			<string>storage.type.float.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(void|char|uchar|string)\b)</string>
			<key>name</key>
			<string>storage.type.misc.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(true|false|null)\b)</string>
			<key>name</key>
			<string>constant.language.source.rapid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(this)\b)</string>
			<key>name</key>
			<string>variable.language.source.rapid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.value.source.rapid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.source.rapid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@[A-Za-z]+\()([A-Za-z0-9_., ]+)(\))</string>
			<key>name</key>
			<string>meta.definition.attribute.source.rapid</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((//).*$\n?)</string>
					<key>name</key>
					<string>comment.line.double-slash.source.rapid</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.rapid</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/\n?</string>
					<key>name</key>
					<string>comment.block.source.rapid</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>compilerCode</key>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>end</key>
			<string>([#\n])</string>
			<key>name</key>
			<string>entity.other.attribute-name</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.enum.source.rapid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.integer.source.rapid</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.enum.source.rapid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)^\s*((?:\b(?:public|internal|local)\b\s)*)(enum)\s+([A-Za-z0-9_]+)\s+([A-Za-z0-9_]+)\b</string>
			<key>name</key>
			<string>meta.definition.enum.source.rapid</string>
		</dict>
		<key>functionPrototype</key>
		<dict>
			<key>name</key>
			<string>meta.definition.function.prototype.source.rapid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.function.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\w)(?:[\t ]+)((\.?[A-Za-z0-9_]+)+)\(</string>
				</dict>
			</array>
		</dict>
		<key>interface</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.interface.source.rapid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.interface.source.rapid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)^\s*((?:\b(?:public|internal|local)\b\s)*)(interface)\s+([A-Za-z0-9_]+)\b</string>
			<key>name</key>
			<string>meta.definition.interface.source.rapid</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((\b|-)[0-9_]+\.[0-9_]+(e\-[0-9]+)?)</string>
					<key>name</key>
					<string>constant.numeric.float.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((\b|-)[0-9_]+([ul]{1,2})?\b)</string>
					<key>name</key>
					<string>constant.numeric.integer.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b0x[\dA-Fa-f_]+\b)</string>
					<key>name</key>
					<string>constant.numeric.hex.source.rapid</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b0b(0|1)+\b)</string>
					<key>name</key>
					<string>constant.numeric.binary.source.rapid</string>
				</dict>
			</array>
		</dict>
		<key>scopeLimit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[(\s*[A-Za-z0-9_]+,?)*\s*\])(?:\s*\{)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.tag.source.rapid</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:\))\s(\[(\s*[A-Za-z0-9_]+,?)*\s*\])(?:\s*(\b|\;))</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.rapid</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.rapid</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.rapid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\.)</string>
					<key>name</key>
					<string>punctuation.definition.string</string>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>begin</key>
			<string>(?x)^\s*((?:\b(?:public|internal|local)\b\s)*)(struct)\s+([A-Za-z0-9_]+)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.source.rapid</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.struct.source.rapid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.struct.source.rapid</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:{)</string>
			<key>name</key>
			<string>meta.definition.struct.source.rapid</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#structInheritance</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>structInheritance</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(implements)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.implements.source.rapid</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[\{@])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.source.rapid</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\s*,?([A-Za-z_]\w*)\b)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rapid</string>
	<key>uuid</key>
	<string>cd4e6b22-a322-4771-8eef-91166b808f3d</string>
</dict>
</plist>
